### PR TITLE
Build out required create and delete repo endpoints

### PR DESCRIPTION
**Pull request by FrancisLevesque**
@nayden PTAL

### CODE REVIEW

**Comment by FrancisLevesque** [comment]
Unfortunately both raw and rubygems don't seem to be supported by Nexus yet.

**Comment by FrancisLevesque** [comment]
The response from support, "We do not have detailed product roadmap information and timing within the support channels. All formats are planned to be implemented but at present there is no specific timeline."

**Comment by FrancisLevesque** [comment]
Will merge this for now and address any comments that come up in patch release versions as this is blocking other work.

**Comment by HailanXyouknow** [comment]
+1 Nice use of shared examples and parameter_builder.rb

**Pull request merged**
